<a href="https://colab.research.google.com/github/MINAADELMARKOS/Data_Opportunites_Analysis/blob/main/Data_Opportunites_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Imoort Libraries**

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.figure_factory as ff
import plotly.io as pio
import plotly.graph_objects as go

In [ ]:
import plotly.io as pio
pio.templates

Templates configuration
-----------------------
    Default template: 'plotly_white'
    Available templates:
        ['ggplot2', 'seaborn', 'simple_white', 'plotly',
         'plotly_white', 'plotly_dark', 'presentation', 'xgridoff',
         'ygridoff', 'gridon', 'none']

In [ ]:
pio.templates.default = 'plotly_white'

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Epslion Project before midproject/Data Analyst Project/DataAnalyst.csv')

# **Explatory Data Analyst**

In [ ]:
df.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True
1,1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1
2,2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),Weâ€™re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1
3,3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
4,4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True

In [ ]:
df.columns[0]

'Unnamed: 0'

In [ ]:
df.drop(columns=['Unnamed: 0'],inplace=True)

In [ ]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),Weâ€™re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1
3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True

In [ ]:
str_columns = list(df.dtypes[df.dtypes == 'object'].index)

for col in str_columns:
  df[col] = df[col].str.lower().str.replace(' ','_')

In [ ]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,"data_analyst,_center_on_immigration_and_justic...",$37k-$66k_(glassdoor_est.),are_you_eager_to_roll_up_your_sleeves_and_harn...,3.2,vera_institute_of_justice\n3.2,"new_york,_ny","new_york,_ny",201_to_500_employees,1961,nonprofit_organization,social_assistance,non-profit,$100_to_$500_million_(usd),-1,true
1,quality_data_analyst,$37k-$66k_(glassdoor_est.),overview\n\nprovides_analytical_and_technical_...,3.8,visiting_nurse_service_of_new_york\n3.8,"new_york,_ny","new_york,_ny",10000+_employees,1893,nonprofit_organization,health_care_services_&_hospitals,health_care,$2_to_$5_billion_(usd),-1,-1
2,"senior_data_analyst,_insights_&_analytics_team...",$37k-$66k_(glassdoor_est.),weâ€™re_looking_for_a_senior_data_analyst_who_ha...,3.4,squarespace\n3.4,"new_york,_ny","new_york,_ny",1001_to_5000_employees,2003,company_-_private,internet,information_technology,unknown_/_non-applicable,godaddy,-1
3,data_analyst,$37k-$66k_(glassdoor_est.),requisition_numberrr-0001939\nremote:yes\nwe_c...,4.1,celerity\n4.1,"new_york,_ny","mclean,_va",201_to_500_employees,2002,subsidiary_or_business_segment,it_services,information_technology,$50_to_$100_million_(usd),-1,-1
4,reporting_data_analyst,$37k-$66k_(glassdoor_est.),about_fanduel_group\n\nfanduel_group_is_a_worl...,3.9,fanduel\n3.9,"new_york,_ny","new_york,_ny",501_to_1000_employees,2009,company_-_private,sports_&_recreation,"arts,_entertainment_&_recreation",$100_to_$500_million_(usd),draftkings,true

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2253 entries, 0 to 2252
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          2253 non-null   object
 1   Salary Estimate    2253 non-null   object
 2   Job Description    2253 non-null   object
 3   Rating             2253 non-null   float64
 4   Company Name       2252 non-null   object
 5   Location           2253 non-null   object
 6   Headquarters       2253 non-null   object
 7   Size               2253 non-null   object
 8   Founded            2253 non-null   int64
 9   Type of ownership  2253 non-null   object
 10  Industry           2253 non-null   object
 11  Sector             2253 non-null   object
 12  Revenue            2253 non-null   object
 13  Competitors        2253 non-null   object
 14  Easy Apply         2253 non-null   object
dtypes: float64(1), int64(1), object(13)
memory usage: 264.1+ KB

In [ ]:
df.isna().sum()

Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         1
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
Easy Apply           0
dtype: int64

In [ ]:
df.describe()

            Rating      Founded
count  2253.000000  2253.000000
mean      3.160630  1398.522858
std       1.665228   901.929251
min      -1.000000    -1.000000
25%       3.100000    -1.000000
50%       3.600000  1979.000000
75%       4.000000  2002.000000
max       5.000000  2019.000000

In [ ]:
df.replace(-1,np.nan,inplace=True)

In [ ]:
df.describe()

            Rating      Founded
count  1981.000000  1593.000000
mean      3.731903  1978.362837
std       0.670332    47.822289
min       1.000000  1682.000000
25%       3.300000  1970.000000
50%       3.700000  1997.000000
75%       4.100000  2006.000000
max       5.000000  2019.000000

In [ ]:
df.isna().sum()

Job Title              0
Salary Estimate        0
Job Description        0
Rating               272
Company Name           1
Location               0
Headquarters           0
Size                   0
Founded              660
Type of ownership      0
Industry               0
Sector                 0
Revenue                0
Competitors            0
Easy Apply             0
dtype: int64

In [ ]:
df.describe(include='O')

,Job Title,Salary Estimate,Job Description,Company Name,Location,Headquarters,Size,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
count,2253,2253,2253,2252,2253,2253,2253,2253,2253,2253,2253,2253,2253
unique,1257,90,2252,1511,253,483,9,15,89,25,14,291,2
top,data_analyst,$42k-$76k_(glassdoor_est.),"job_description\ninterpret_data,_analyze_resul...","staffigo_technical_services,_llc\n5.0","new_york,_ny","new_york,_ny",51_to_200_employees,company_-_private,-1,information_technology,unknown_/_non-applicable,-1,-1
freq,411,57,2,58,310,206,421,1273,353,570,615,1732,2173

In [ ]:
df.replace('-1',np.nan,inplace=True)

In [ ]:
df.describe(include='O')

,Job Title,Salary Estimate,Job Description,Company Name,Location,Headquarters,Size,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
count,2253,2252,2253,2252,2253,2081,2090,2090,1900,1900,2090,521,80
unique,1257,89,2252,1511,253,482,8,14,88,24,13,290,1
top,data_analyst,$42k-$76k_(glassdoor_est.),"job_description\ninterpret_data,_analyze_resul...","staffigo_technical_services,_llc\n5.0","new_york,_ny","new_york,_ny",51_to_200_employees,company_-_private,it_services,information_technology,unknown_/_non-applicable,"adecco,_manpower",true
freq,411,57,2,58,310,206,421,1273,325,570,615,14,80

In [ ]:
df.isna().sum()

Job Title               0
Salary Estimate         1
Job Description         0
Rating                272
Company Name            1
Location                0
Headquarters          172
Size                  163
Founded               660
Type of ownership     163
Industry              353
Sector                353
Revenue               163
Competitors          1732
Easy Apply           2173
dtype: int64

# **Handeling Missing Data**

In [ ]:
df['Easy Apply'].to_frame().head(6)

  Easy Apply
0       true
1        NaN
2        NaN
3        NaN
4       true
5        NaN

In [ ]:
df['Easy Apply'].replace(np.nan,"apply on company website",inplace=True)

In [ ]:
df['Easy Apply'].to_frame().head(6)

                 Easy Apply
0                      true
1  apply on company website
2  apply on company website
3  apply on company website
4                      true
5  apply on company website

In [ ]:
df['Easy Apply'].value_counts()

apply on company website    2173
true                          80
Name: Easy Apply, dtype: int64

In [ ]:
df.isna().sum()

Job Title               0
Salary Estimate         1
Job Description         0
Rating                272
Company Name            1
Location                0
Headquarters          172
Size                  163
Founded               660
Type of ownership     163
Industry              353
Sector                353
Revenue               163
Competitors          1732
Easy Apply              0
dtype: int64

In [ ]:
df.dropna(subset=['Salary Estimate','Company Name'],inplace = True)

In [ ]:
df.isna().sum()

Job Title               0
Salary Estimate         0
Job Description         0
Rating                271
Company Name            0
Location                0
Headquarters          171
Size                  162
Founded               659
Type of ownership     162
Industry              352
Sector                352
Revenue               162
Competitors          1730
Easy Apply              0
dtype: int64

In [ ]:
px.histogram(df,x='Rating')

In [ ]:
px.box(df,x='Rating',template ='simple_white')

In [ ]:
px.scatter(df ,x='Founded' ,y='Rating' , marginal_y="histogram",template ='simple_white')

In [ ]:
px.imshow(df.corr().round(2), text_auto=True)

In [ ]:
df.isna().sum()

Job Title               0
Salary Estimate         0
Job Description         0
Rating                271
Company Name            0
Location                0
Headquarters          171
Size                  162
Founded               659
Type of ownership     162
Industry              352
Sector                352
Revenue               162
Competitors          1730
Easy Apply              0
dtype: int64

In [ ]:
df['Rating'].median()

3.7

In [ ]:
df['Rating'].fillna(df['Rating'].median(),inplace=True)

In [ ]:
df.isna().sum()

Job Title               0
Salary Estimate         0
Job Description         0
Rating                  0
Company Name            0
Location                0
Headquarters          171
Size                  162
Founded               659
Type of ownership     162
Industry              352
Sector                352
Revenue               162
Competitors          1730
Easy Apply              0
dtype: int64

In [ ]:
pd.pivot_table(df, values='Job Title', index=['Salary Estimate'],
                    columns=['Size'], aggfunc='count', fill_value=0)

Size,10000+_employees,1001_to_5000_employees,1_to_50_employees,201_to_500_employees,5001_to_10000_employees,501_to_1000_employees,51_to_200_employees,unknown
Salary Estimate,,,,,,,,
$110k-$190k_(glassdoor_est.),3,7,3,3,1,4,6,0
$113k-$132k_(glassdoor_est.),4,4,4,3,3,3,4,1
$24k-$48k_(glassdoor_est.),7,6,4,3,3,3,3,0
$26k-$47k_(glassdoor_est.),3,2,4,1,1,6,9,0
$27k-$52k_(glassdoor_est.),9,4,4,2,2,5,3,0
...,...,...,...,...,...,...,...,...
$89k-$151k_(glassdoor_est.),5,4,4,4,2,2,5,0
$93k-$159k_(glassdoor_est.),2,5,3,6,1,3,5,0
$97k-$129k_(glassdoor_est.),6,3,6,3,2,1,5,1
$98k-$114k_(glassdoor_est.),5,3,5,3,0,6,5,1
$99k-$178k_(glassdoor_est.),3,4,4,4,1,3,6,1

In [ ]:
df[df['Headquarters'].isna()]

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
11,data_analyst,$37k-$66k_(glassdoor_est.),bulbhead_is_currently_seeking_a_data_analyst_t...,3.7,bulbhead,"fairfield,_nj",NaN,1_to_50_employees,NaN,company_-_private,NaN,NaN,unknown_/_non-applicable,NaN,apply on company website
34,data_analyst_(games),$46k-$87k_(glassdoor_est.),carry1st_is_the_leading_mobile_game_publisher_...,3.7,carry1st,"new_york,_ny",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,apply on company website
55,data_reporting_analyst,$46k-$87k_(glassdoor_est.),overviewthe_data_analyst_is_a_new_position_in_...,3.7,nadap_nys_inc.,"new_york,_ny",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,apply on company website
68,data_science_analyst,$51k-$88k_(glassdoor_est.),job_details\n\nlevel\n\nexperienced\n\njob_loc...,3.7,greater_new_york_mutual_insurance_companies_(gny),"new_york,_ny",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,apply on company website
90,data_analyst,$51k-$87k_(glassdoor_est.),nyu_grossman_school_of_medicine_is_one_of_the_...,3.7,nyu_langone_medical_center,"new_york,_ny",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,apply on company website
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2200,data_analyst,$49k-$91k_(glassdoor_est.),role_data_analyst_duration12+_months_location_...,3.7,"techaspect_solutions,_inc._dba_ta_digital","centennial,_co",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,apply on company website
2202,financial_data_analyst,$49k-$91k_(glassdoor_est.),position:financial_data_analystjob_description...,3.7,black_knight_financial_technology_solutions,"denver,_co",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,apply on company website
2239,senior_contract_data_analyst,$78k-$104k_(glassdoor_est.),overviewamyx_is_seeking_to_hire_a_senior_contr...,3.7,"amyx,_iinc.","aurora,_co",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,apply on company website
2246,"technical_business_analyst_(sql,_data_analytic...",$78k-$104k_(glassdoor_est.),spiceorb_is_looking_for_technical_business_ana...,3.7,spiceorb,"denver,_co",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,apply on company website
2250,"technical_business_analyst_(sql,_data_analytic...",$78k-$104k_(glassdoor_est.),"title:_technical_business_analyst_(sql,_data_a...",3.7,spiceorb,"denver,_co",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,apply on company website

In [ ]:
df['Headquarters'].fillna(df['Location'],inplace=True)

In [ ]:
df.isna().sum()

Job Title               0
Salary Estimate         0
Job Description         0
Rating                  0
Company Name            0
Location                0
Headquarters            0
Size                  162
Founded               659
Type of ownership     162
Industry              352
Sector                352
Revenue               162
Competitors          1730
Easy Apply              0
dtype: int64

In [ ]:
df['Size'].value_counts()

51_to_200_employees        420
10000+_employees           375
1001_to_5000_employees     348
1_to_50_employees          347
201_to_500_employees       249
501_to_1000_employees      211
5001_to_10000_employees     97
unknown                     42
Name: Size, dtype: int64

In [ ]:
df['Size'].fillna('Unknown',inplace=True)

In [ ]:
df.isna().sum()

Job Title               0
Salary Estimate         0
Job Description         0
Rating                  0
Company Name            0
Location                0
Headquarters            0
Size                    0
Founded               659
Type of ownership     162
Industry              352
Sector                352
Revenue               162
Competitors          1730
Easy Apply              0
dtype: int64

In [ ]:
df['Founded'].to_frame().head()

   Founded
0   1961.0
1   1893.0
2   2003.0
3   2002.0
4   2009.0

In [ ]:
df['Founded'].mode()[0]

2008.0

In [ ]:
df['Founded'].fillna(df['Founded'].mode()[0], inplace = True)

In [ ]:
df.isna().sum()

Job Title               0
Salary Estimate         0
Job Description         0
Rating                  0
Company Name            0
Location                0
Headquarters            0
Size                    0
Founded                 0
Type of ownership     162
Industry              352
Sector                352
Revenue               162
Competitors          1730
Easy Apply              0
dtype: int64

In [ ]:
df.columns

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'Easy Apply'],
      dtype='object')

In [ ]:
df['Industry'].mode()[0]

'it_services'

In [ ]:
columns = ['Industry', 'Sector', 'Revenue', 'Competitors','Type of ownership']

for col in columns:
  df[col].fillna(df['Industry'].mode()[0],inplace=True)

In [ ]:
df.isna().sum()

Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         0
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
Easy Apply           0
dtype: int64

In [ ]:
top_jobs = df.groupby('Job Title').agg({
    "Easy Apply":"count"
}).reset_index().sort_values('Easy Apply',ascending=False).head(30)

In [ ]:
top_jobs

                                    Job Title  Easy Apply
233                              Data Analyst         404
996                       Senior Data Analyst          90
763                       Junior Data Analyst          30
136                     Business Data Analyst          28
1156                         Sr. Data Analyst          21
364                           Data Analyst II          17
375                       Data Analyst Junior          17
552                      Data Quality Analyst          17
514                   Data Governance Analyst          16
774                         Lead Data Analyst          15
560                    Data Reporting Analyst          13
682                    Financial Data Analyst          12
358                            Data Analyst I          11
369                          Data Analyst III          11
1123                          Sr Data Analyst           9
809                    Marketing Data Analyst           9
529                   Data Management Analyst           8
608                    Data Warehouse Analyst           8
1236                   Technical Data Analyst           7
948                          SQL Data Analyst           7
564                      Data Science Analyst           7
579                     Data Security Analyst           6
712                   Healthcare Data Analyst           6
924                     Research Data Analyst           6
183                     Clinical Data Analyst           6
834      NY Healthcare Data/Reporting Analyst           5
878                      Product Data Analyst           5
1073           Senior Healthcare Data Analyst           5
370   Data Analyst III (Healthcare Analytics)           5
994              Senior Contract Data Analyst           4

In [ ]:
px.bar(top_jobs,x='Job Title',y='Easy Apply')

In [ ]:
df['Job Title'][0]

'Data Analyst, Center on Immigration and Justice (CIJ)'

In [ ]:
v = 'Data Analyst, Center on Immigration and Justice (CIJ)'

In [ ]:
v.lower().replace('(','').replace(')','')

'data analyst, center on immigration and justice cij'

In [ ]:
def clean_job_title(job_title):

    if 'III' in job_title:
        job_title = job_title.replace('III', '')
        job_title = 'lead ' + job_title
    elif 'II' in job_title:
        job_title = job_title.replace('II', '')
        job_title = 'senior ' + job_title
    elif 'I' in job_title:
        job_title = job_title.replace('I', '')
        job_title = 'junior ' + job_title

    job_title = job_title.lower().replace('.', '').replace('sr', 'senior').replace('jr', 'junior').replace('/', ' ')

    if job_title.endswith('junior'):
        job_title = job_title.replace('junior', '')
        job_title = 'junior ' + job_title




    return job_title

In [ ]:
df['Job Title'] = df['Job Title'].apply(clean_job_title)

In [ ]:
df['Job Title'][12]

'data analyst'

In [ ]:
top_jobs = df.groupby('Job Title').agg({
    "Easy Apply":"count"
}).reset_index().sort_values('Easy Apply',ascending=False).head(30)

In [ ]:
top_jobs

                                      Job Title  Easy Apply
154                                data analyst         410
1009                        senior data analyst         121
607                         junior data analyst          33
99                        business data analyst          32
608                        junior data analyst           28
1010                       senior data analyst           17
416                        data quality analyst          17
390                     data governance analyst          16
801                           lead data analyst          15
425                      data reporting analyst          14
511                      financial data analyst          12
802                          lead data analyst           11
840                      marketing data analyst           9
467                      data warehouse analyst           8
396                     data management analyst           8
427                        data science analyst           7
1172                           sql data analyst           7
1208                     technical data analyst           7
1119             senior healthcare data analyst           6
940                       research data analyst           6
992                senior business data analyst           6
532                     healthcare data analyst           6
440                       data security analyst           6
904                        product data analyst           6
125                       clinical data analyst           6
870        ny healthcare data reporting analyst           5
874                     operations data analyst           5
803   lead data analyst  (healthcare analytics)           5
634                   junior data analyst ntern           4
62                             big data analyst           4

In [ ]:
px.bar(top_jobs,x='Job Title',y='Easy Apply')

In [ ]:
df.columns

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'Easy Apply'],
      dtype='object')

In [ ]:
df['Revenue'].unique()

array(['$100 to $500 million (USD)', '$2 to $5 billion (USD)',
       'Unknown / Non-Applicable', '$50 to $100 million (USD)',
       '$1 to $2 billion (USD)', '$5 to $10 billion (USD)',
       '$1 to $5 million (USD)', '$25 to $50 million (USD)',
       '$10+ billion (USD)', 'Less than $1 million (USD)',
       '$10 to $25 million (USD)', 'IT Services',
       '$500 million to $1 billion (USD)', '$5 to $10 million (USD)'],
      dtype=object)

In [ ]:
temp = '$42K-$76K (Glassdoor est.)'

In [ ]:
temp.split('-')[1]

'$76K (Glassdoor est.)'

In [ ]:
int(''.join(list(filter(str.isdigit, temp.split('-')[0]))))

42

In [ ]:
df.columns

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'Easy Apply'],
      dtype='object')

In [ ]:
def get_min_salary(minSalary):
  minSalary = minSalary.lower()
  minSalary = minSalary.split('-')[0]
  minSalary_num = int(''.join(list(filter(str.isdigit,minSalary))))

  if 'k' in minSalary:
    minSalary_num = minSalary_num *1000

  return minSalary_num

In [ ]:
df['min_salary']=df['Salary Estimate'].apply(get_min_salary)

In [ ]:
df['min_salary']

0       37000
1       37000
2       37000
3       37000
4       37000
        ...
2248    78000
2249    78000
2250    78000
2251    78000
2252    78000
Name: min_salary, Length: 2251, dtype: int64

In [ ]:
def max_salary(maxSalary):
  maxSalary = maxSalary.lower()
  maxSalary = maxSalary.split('-')[1]
  maxSalary_Num = int(''.join(list(filter(str.isdigit,maxSalary))))
  if 'k' in maxSalary:
    maxSalary_Num = maxSalary_Num *1000

  return maxSalary_Num

In [ ]:
df['max_salary']=df['Salary Estimate'].apply(max_salary)

In [ ]:
df

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,min_salary,max_salary
0,"junior data analyst, center on mmigration and ...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961.0,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),IT Services,True,37000,66000
1,quality data analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893.0,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),IT Services,apply on company website,37000,66000
2,"junior senior data analyst, nsights & analytic...",$37K-$66K (Glassdoor est.),Weâ€™re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003.0,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,apply on company website,37000,66000
3,data analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002.0,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),IT Services,apply on company website,37000,66000
4,reporting data analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009.0,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True,37000,66000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248,junior rqs - hha - 201900004460 -1q data secur...,$78K-$104K (Glassdoor est.),Maintains systems to protect data from unautho...,2.5,"Avacend, Inc.\n2.5","Denver, CO","Alpharetta, GA",51 to 200 employees,2008.0,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,IT Services,apply on company website,78000,104000
2249,senior data analyst (corporate audit),$78K-$104K (Glassdoor est.),Position:\nSenior Data Analyst (Corporate Audi...,2.9,Arrow Electronics\n2.9,"Centennial, CO","Centennial, CO",10000+ employees,1935.0,Company - Public,Wholesale,Business Services,$10+ billion (USD),"Avnet, Ingram Micro, Tech Data",apply on company website,78000,104000
2250,"technical business analyst (sql, data analytic...",$78K-$104K (Glassdoor est.),"Title: Technical Business Analyst (SQL, Data a...",3.7,Spiceorb,"Denver, CO","Denver, CO",Unknown,2008.0,IT Services,IT Services,IT Services,IT Services,IT Services,apply on company website,78000,104000
2251,"data analyst 3, customer experience",$78K-$104K (Glassdoor est.),Summary\n\nResponsible for working cross-funct...,3.1,Contingent Network Services\n3.1,"Centennial, CO","West Chester, OH",201 to 500 employees,1984.0,Company - Private,Enterprise Software & Network Solutions,Information Technology,$25 to $50 million (USD),IT Services,apply on company website,78000,104000
2252,senior quality data analyst,$78K-$104K (Glassdoor est.),"You.\n\nYou bring your body, mind, heart and s...",3.4,SCL Health\n3.4,"Broomfield, CO","Broomfield, CO",10000+ employees,1864.0,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),"Centura Health, HealthONE, Denver Health and H...",apply on company website,78000,104000

In [ ]:
# python, sql, excel, tableau, git, power bi, statistics, mathematics
df['python'] = df['Job Description'].str.contains('python', case=False, na=False)
df['sql'] = df['Job Description'].str.contains('sql', case=False, na=False)
df['excel'] = df['Job Description'].str.contains('excel', case=False, na=False)
df['dash'] = df['Job Description'].str.contains('dash', case=False, na=False)
df['spark'] = df['Job Description'].str.contains('spark', case=False, na=False)
df['tableau'] = df['Job Description'].str.contains('tableau', case=False, na=False)
df['git'] = df['Job Description'].str.contains('git', case=False, na=False)

In [ ]:
df['sql'].value_counts()

True     1387
False     864
Name: sql, dtype: int64

In [ ]:
df.columns

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'Easy Apply', 'min_salary', 'max_salary', 'python', 'sql', 'excel',
       'dash', 'spark', 'tableau', 'git'],
      dtype='object')

## **Count Skilles required in jobs**

In [ ]:
df[['python', 'excel', 'sql','dash', 'spark', 'tableau', 'git']].apply(pd.value_counts)

       python  excel   sql  dash  spark  tableau   git
False    1614    899   864  1706   2162     1631  1953
True      637   1352  1387   545     89      620   298

## **top 5 jobs market needed**

In [ ]:
df[['Job Title']].apply(pd.value_counts).head().reset_index()

                   index  Job Title
0           data analyst        410
1    senior data analyst        121
2    junior data analyst         33
3  business data analyst         32
4   junior data analyst          28

## **Jobs with skiils required**

In [ ]:
df_ne = df.groupby('Job Title').agg({'python':'sum',
                            'excel':'sum',
                            'sql':'sum',
                            'dash':'sum',
                            'spark':'sum',
                            'tableau':'sum',
                            'git':'sum'}).reset_index().sort_values(by='python',ascending=False).head(5)

In [ ]:
df_ne

,Job Title,python,excel,sql,dash,spark,tableau,git
154,data analyst,125,240,301,115,21,110,51
1009,senior data analyst,68,66,105,53,7,64,29
99,business data analyst,11,20,25,13,1,12,2
801,lead data analyst,5,7,13,7,2,10,3
803,lead data analyst (healthcare analytics),5,5,5,3,0,5,0

In [ ]:
px.bar(df_ne , x= 'Job Title' ,y=['python','excel','sql',	'dash',	'spark',	'tableau'	,'git'])

In [ ]:
df.columns

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'Easy Apply', 'min_salary', 'max_salary', 'python', 'sql', 'excel',
       'dash', 'spark', 'tableau', 'git'],
      dtype='object')

## **Top 10 Fields needed tech included sector**

In [ ]:
df.groupby('Sector').agg({'Job Title':'count'}).reset_index().sort_values(by='Job Title',ascending=False).head()

                    Sector  Job Title
12  Information Technology        570
4        Business Services        523
11             IT Services        352
8                  Finance        169
10             Health Care        151

In [ ]:
df_pie_sec =df['Sector'].value_counts().to_frame().reset_index().head(10)

In [ ]:
px.pie(df_pie_sec, values='Sector', names='index')

## **Top 10 Fields needed tech included industry**

In [ ]:
df.columns

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'Easy Apply', 'min_salary', 'max_salary', 'python', 'sql', 'excel',
       'dash', 'spark', 'tableau', 'git'],
      dtype='object')

In [ ]:
df_pie_ind = df['Industry'].value_counts().to_frame().reset_index().head(10)

In [ ]:
px.pie(df_pie_ind, values='Industry',names='index')

## **Relation Between revenue and average salary**

In [ ]:
df.columns

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'Easy Apply', 'min_salary', 'max_salary', 'python', 'sql', 'excel',
       'dash', 'spark', 'tableau', 'git'],
      dtype='object')

In [ ]:
# The salary for each player's age with the prefered foot
px.histogram(df, x='Revenue',y='min_salary')

In [ ]:
import re

In [ ]:
def reven_handel(value):

  value = value.lower()

  if 'unknown' in value:
    return np.nan

  elif 'to' in value:
    # calculate average

    lower_val,upper_val = value.split('to')

    min_val = int(re.findall(r'\d+', lower_val)[0])
    max_val = int(re.findall(r'\d+', upper_val)[0])

    if 'billion' in lower_val:
      min_val = min_val*1000
    if 'billion' in upper_val:
      max_val = max_val*1000

    average_rev = int((min_val + max_val) / 2)

    return average_rev

  elif ('less' in value) or ('+' in value):
    number = int(re.findall(r'\d+', value)[0])

    if 'billion' in value:
      number*=10**3
    return number

In [ ]:
df['Revenue_cleaned']=df['Revenue'].apply(reven_handel)

In [ ]:
df['Revenue_cleaned']

0         300.0
1        2501.0
2           NaN
3          75.0
4         300.0
         ...
2248        NaN
2249    10000.0
2250        NaN
2251       37.0
2252     2501.0
Name: Revenue_cleaned, Length: 2251, dtype: float64

In [ ]:
px.histogram(df, x='Revenue_cleaned',y='min_salary')

In [ ]:
def reven_handel(value):

  if 'unknown' in value:
    return np.nan

  if 'to' in value:

    lower_val,upper_val = value.split('to')

    min_val = int(re.findall(r'\d+', lower_val)[0])* 10**3
    max_val = int(re.findall(r'\d+', upper_val)[0])* 10**3

    average_rev = int((min_val + max_val) / 2)
    print(average_rev)

In [ ]:
df['Revenue'][0].lower().split('to')

['$100 ', ' $500 million (usd)']

In [ ]:
df['Revenue'][1].lower().split('to')

['$2 ', ' $5 billion (usd)']

In [ ]:
df['Revenue'][2].lower().split('to')

['unknown / non-applicable']

In [ ]:
df['Revenue'][3].lower().split('to')

['$50 ', ' $100 million (usd)']